### ISSUE TITLE
How to change titleLabel textColor ?

### ISSUE THREAD

**Issue by skrew** [alldritt/EurekaColorPicker#12]
Hi,

How to change this color ? (titled: "Color Picker 3")

<img width="375" alt="screen shot 2018-11-10 at 00 01 21" src="https://user-images.githubusercontent.com/738170/48292769-138ebf80-e47c-11e8-9213-1d18ab65b7c7.png">

Thanks

**Update**: Changing color in `cellUpdate` works with `InlineColorPickerRow` but not with `ColorPickerRow`

**Comment by alldritt** [comment]
The title is displayed using a UILabel.  You can configure this label in `.cellSetup`:

```
                .cellSetup { (cell, row) in
                    cell.titleLabel.textColor = .blue
                    // ...
                }
```

**Comment by skrew** [comment]
Yes i have tested that, but i get `'titleLabel' is inaccessible due to 'internal' protection level` error.

But even passing titleLabel public don't works, label is still black.

**Comment by alldritt** [comment]
I've pushed some changes to make the properties of the `ColorPickerCell` object public.  Turns out, for `InlineColorPickerRow`, you need to alter the color in the update callback:

```
                        .cellUpdate { (cell, row) in
                            cell.textLabel?.textColor = .green
                        }
```

For `ColorPickerRow` you can use the `.cellSetup` or the `.cellUpdate` callbacks to alter the `cell.titleLabel.textColor`.
